import Appointment from "./Appointment";
import Favourite from "./Favourite";
import Home from "./Home";
import Profile from "./Profile";
import Settings from "./Settings";
import SignIn from "./SignIn";
import SignUp from "./SignUp";
import SignUpExtra from "./SignUpExtra";
import Message from "./Message";
import ChatRoom from "./Message/ChatRoom";
import SearchResult from "./Home/SearchResult";

export { Appointment as AppointmentScreen };
export { Favourite as FavouriteScreen };
export { Home as HomeScreen };
export { Profile as ProfileScreen };
export { Settings as SettingsScreen };
export { SignIn as SignInScreen };
export { SignUp as SignUpScreen };
export { SignUpExtra as SignUpExtraScreen };
export { Message as MessageScreen };
export { ChatRoom as ChatRoomScreen };
export { SearchResult as SearchResultScreen };
